spring:
  application:
    name: CostAccountingSystem
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/cost_accounting_system
